### ISSUE TITLE
ANPR suggestion

### ISSUE THREAD

**Issue by judgegritter** [LondonsBlueLine/tracker#482] opened 2022-10-27 12:32 UTC
Add an option for civilians to use an ANPR script. Some servers use it as the civs use commands such as 'setplate' and then commands to allow the script to pick up the plate around the map when hitting ANPR cameras. This will make it that tad more realistic for the officers instead of civs using 999.
If this is available then apologies but I'not aware.

Previous one was closed without actually understanding my actual suggestion. I am fully aware civs can add vehicles under their names. However this does not permit civs to add "warning markers" to vehicles that would flag up on an ANPR script for officers to use. 

W/M can be anything from ACT markers (low, medium and high - though high is usually on a 'hotlist' and will be the priority for any force if resources allow it to be stopped) and the ACT markers could misper, wanted, county lines or be simple 'stop and check the documents and obtain details' which could also be for numerous reasons whether DVLA want confirmation or the vehicle has history of red light/speeding offences and no response to the letters issued. I could go on for ages tbh.

**Comment by judgegritter** [comment] 2022-10-27 12:36
Would also be nice to be able to change the plates manually at a garage or something so that we can also use cloned plates which links in with the warning markers

**Comment by colossalengineer** [comment] 2022-10-27 13:11
@judgegritter From watching your stream your using FivePD ANPR. Num3 Activates ANPR linked to CAD.

**Comment by judgegritter** [comment] 2022-10-27 18:17
> @judgegritter From watching your stream your using FivePD ANPR. Num3 Activates ANPR linked to CAD.

Which is fine... if it was possible to actually add markers that isn't just "stolen"

**Comment by jxckUK** [comment] 2022-10-28 16:00
> If this is available then apologies but I'not aware.
> 

It does yes, ensure you're not using "ALPR" which is FivePDs version that is no longer used.

> Previous one was closed without actually understanding my actual suggestion. I am fully aware civs can add vehicles under their names. However this does not permit civs to add "warning markers" to vehicles that would flag up on an ANPR script for officers to use.

It wasn't closed, it is still active: https://github.com/LondonsBlueLine/tracker/issues/460

As discussed there, you can add these markers but we're working on a way to allow you to do that as a civilian.

> W/M can be anything from ACT markers (low, medium and high - though high is usually on a 'hotlist' and will be the priority for any force if resources allow it to be stopped) and the ACT markers could misper, wanted, county lines or be simple 'stop and check the documents and obtain details' which could also be for numerous reasons whether DVLA want confirmation or the vehicle has history of red light/speeding offences and no response to the letters issued. I could go on for ages tbh.

If we need to add new markers to the CAD so they can be assigned, we can do so but this would need to come from Silver/Gold command.

Closing this one as a duplicate of https://github.com/LondonsBlueLine/tracker/issues/460.

**Closed by jxckUK** 2022-10-28 16:00 UTC
Labels: enhancement
