### ISSUE TITLE
Can we please get a TSG shield added

### ISSUE THREAD

**Issue by Kay182i** [LondonsBlueLine/tracker#297] opened 2022-07-18 21:34 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jxckUK** [comment] 2022-07-19 19:46
Duplicate of https://github.com/LondonsBlueLine/tracker/issues/292

**Closed by jxckUK** 2022-07-19 19:46 UTC
Labels: enhancement
