### ISSUE TITLE
BTP uniform EUP additions

### ISSUE THREAD

**Issue by BA98x** [LondonsBlueLine/tracker#382] opened 2022-08-29 13:21 UTC
I have made 2 or 3 new uniforms on the dev can they be moved into the lockers for main.

They are on the list in the other issue.

**Comment by jxckUK** [comment] 2022-08-29 13:23
Duplicate of https://github.com/LondonsBlueLine/tracker/issues/380

**Closed by jxckUK** 2022-08-29 13:23 UTC
Labels: enhancement
